---
- name: Install glances
  hosts: all
  roles:
    - role: glances
      tags:
        - glances
    - role: exporters
      tags:
        - exporters
    - role: promtail
      tags:
        - promtail
