# SPDX-License-Identifier: MIT-0
---
# handlers file for glances
- name: Start and enable glances service
  ansible.builtin.service:
    name: glances
    state: restarted
    enabled: true
  become: true
