# SPDX-License-Identifier: MIT-0
---
# tasks file for glances
- name: Install glances
  community.general.pacman:
    name: glances
    executable: yay
    state: present
- name: Configure glances
  ansible.builtin.template:
    src: glances.conf
    dest: /etc/glances/glances.conf
    owner: root
    group: root
    mode: ug+rw
  become: true
- name: Update glances service
  ansible.builtin.copy:
    src: glances.service
    dest: /usr/lib/systemd/system/glances.service
    owner: root
    group: root
    mode: ug+rw
  become: true
- name: Start and enable glances service
  ansible.builtin.service:
    name: glances
    state: restarted
    enabled: true
  become: true
