# SPDX-License-Identifier: MIT-0
---
# tasks file for glances
- name: Install glances
  community.general.pacman:
    name: >-
      {{ glances_item }}
    executable: yay
    state: present
  loop: >-
    {{ glances_packages }}
  loop_control:
    loop_var: glances_item
- name: Configure glances
  ansible.builtin.template:
    src: glances.conf
    dest: /etc/glances/glances.conf
    owner: root
    group: root
    mode: ug+rw
  become: true
- name: Update glances service
  ansible.builtin.copy:
    src: glances.service
    dest: /usr/lib/systemd/system/glances.service
    owner: root
    group: root
    mode: ug+rw
  become: true
- name: Install glances harder
  ansible.builtin.pip:
    name: >-
      {{ glances_item }}
    virtualenv: /etc/glances
  become: true
  loop: >-
    {{ glances_pip_packages }}
  loop_control:
    loop_var: glances_item
  notify:
    - Start and enable glances service
